export * from './authenticationController.service';
import { AuthenticationControllerService } from './authenticationController.service';
export * from './carrelloController.service';
import { CarrelloControllerService } from './carrelloController.service';
export * from './dettagliNoleggioController.service';
import { DettagliNoleggioControllerService } from './dettagliNoleggioController.service';
export * from './dettagliOrdineController.service';
import { DettagliOrdineControllerService } from './dettagliOrdineController.service';
export * from './dipendenteController.service';
import { DipendenteControllerService } from './dipendenteController.service';
export * from './filialeController.service';
import { FilialeControllerService } from './filialeController.service';
export * from './indirizzoUtenteController.service';
import { IndirizzoUtenteControllerService } from './indirizzoUtenteController.service';
export * from './metodoPagamentoController.service';
import { MetodoPagamentoControllerService } from './metodoPagamentoController.service';
export * from './noleggioController.service';
import { NoleggioControllerService } from './noleggioController.service';
export * from './ordineController.service';
import { OrdineControllerService } from './ordineController.service';
export * from './organizzatoreEventiController.service';
import { OrganizzatoreEventiControllerService } from './organizzatoreEventiController.service';
export * from './prodottoController.service';
import { ProdottoControllerService } from './prodottoController.service';
export * from './recensioneController.service';
import { RecensioneControllerService } from './recensioneController.service';
export * from './sampleEntityController.service';
import { SampleEntityControllerService } from './sampleEntityController.service';
export * from './stockController.service';
import { StockControllerService } from './stockController.service';
export * from './utenteController.service';
import { UtenteControllerService } from './utenteController.service';
export * from './vantaggioController.service';
import { VantaggioControllerService } from './vantaggioController.service';
export const APIS = [AuthenticationControllerService, CarrelloControllerService, DettagliNoleggioControllerService, DettagliOrdineControllerService, DipendenteControllerService, FilialeControllerService, IndirizzoUtenteControllerService, MetodoPagamentoControllerService, NoleggioControllerService, OrdineControllerService, OrganizzatoreEventiControllerService, ProdottoControllerService, RecensioneControllerService, SampleEntityControllerService, StockControllerService, UtenteControllerService, VantaggioControllerService];
