version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_webapp
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: webapp
      MYSQL_USER: webappuser
      MYSQL_PASSWORD: webapppassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network  # Aggiungi il servizio db alla rete comune

  backend:
    build: .
    container_name: springbootbackend
    ports:
      - "8080:8080"
    volumes:
      - .:/app  # Monta la cartella del progetto come volume
    networks:
      - app_network  # Collega il backend alla rete comune

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
    name: app_network
