version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: angular_env
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
      - openapi-spec:/openapi

      # Evita problemi di permessi con i moduli
    networks:
      - app_network  # Collega il backend alla rete comune
    stdin_open: true
    tty: true
    ports:
      - "4200:4200"
    command: >
      bash -c "
        if [ \"$API_UPDATE\" != \"false\" ]; then
          npm run generate:api;
        fi &&
      
        if [ ! -d \"/app/node_modules\" ]|| [ \"$PKG_UPDATE\" = \"true\" ]; then
          echo 'node_modules non trovata, installo le dipendenze...'
          npm install
        fi
        echo 'Avvio il server Angular' &&
        ng serve --host 0.0.0.0 --proxy-config proxy.conf.json 
      "

volumes:
  openapi-spec:
    external: true

networks:
  app_network:
    external: true