/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateOrderDTO { 
    dataAcquisto?: string;
    dataConsegna?: string;
    spedizioneGratuita?: boolean;
    totale?: number;
    stato?: CreateOrderDTO.StatoEnum;
}
export namespace CreateOrderDTO {
    export const StatoEnum = {
        InElaborazione: 'IN_ELABORAZIONE',
        Spedito: 'SPEDITO',
        InConsegna: 'IN_CONSEGNA',
        Consegnato: 'CONSEGNATO',
        Annullato: 'ANNULLATO'
    } as const;
    export type StatoEnum = typeof StatoEnum[keyof typeof StatoEnum];
}


