/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateUserDTO { 
    nome?: string;
    cognome?: string;
    email?: string;
    password?: string;
    dataDiNascita?: string;
    pathImmagine?: string;
    sesso?: CreateUserDTO.SessoEnum;
}
export namespace CreateUserDTO {
    export const SessoEnum = {
        Maschio: 'MASCHIO',
        Femmina: 'FEMMINA',
        NonSpecificato: 'NON_SPECIFICATO'
    } as const;
    export type SessoEnum = typeof SessoEnum[keyof typeof SessoEnum];
}


