/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateProductDTO { 
    nome?: string;
    descrizione?: string;
    prezzo?: number;
    marca?: string;
    isRentable?: boolean;
    costoGiornaliero?: number;
    pathImmagine?: string;
}

