/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateUserAddressDTO { 
    via?: string;
    civico?: string;
    cap?: string;
    citta?: string;
    provincia?: string;
    nazione?: string;
    isDefault?: boolean;
    tipologia?: CreateUserAddressDTO.TipologiaEnum;
    utenteId?: string;
    utenteNome?: string;
    utenteCognome?: string;
}
export namespace CreateUserAddressDTO {
    export const TipologiaEnum = {
        Spedizione: 'SPEDIZIONE'
    } as const;
    export type TipologiaEnum = typeof TipologiaEnum[keyof typeof TipologiaEnum];
}


