/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResponseRentalDTO { 
    id?: string;
    dataInizio?: string;
    dataScadenza?: string;
    dataRestituzione?: string;
    dataPagamento?: string;
    totale?: number;
}

