/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResponseBranchDTO { 
    id?: string;
    indirizzo?: string;
    nome?: string;
    telefono?: string;
    email?: string;
}

