/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResponseEmployeeDTO { 
    id?: string;
    nome?: string;
    cognome?: string;
    email?: string;
    dataDiNascita?: string;
    tipologia?: ResponseEmployeeDTO.TipologiaEnum;
    pathImmagine?: string;
    sesso?: ResponseEmployeeDTO.SessoEnum;
    dataRegistrazione?: string;
    punti?: number;
    vantaggioId?: string;
    stipendio?: number;
    scadenzaContratto?: string;
    dataAssunzione?: string;
    filialeId?: string;
}
export namespace ResponseEmployeeDTO {
    export const TipologiaEnum = {
        Utente: 'UTENTE',
        Dipendente: 'DIPENDENTE',
        OrganizzatoreEventi: 'ORGANIZZATORE_EVENTI'
    } as const;
    export type TipologiaEnum = typeof TipologiaEnum[keyof typeof TipologiaEnum];
    export const SessoEnum = {
        Maschio: 'MASCHIO',
        Femmina: 'FEMMINA',
        NonSpecificato: 'NON_SPECIFICATO'
    } as const;
    export type SessoEnum = typeof SessoEnum[keyof typeof SessoEnum];
}


