/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResponseBenefitDTO { 
    id?: string;
    nome?: string;
    sconto?: number;
    punteggioMinimo?: number;
    punteggioMassimo?: number;
}

