/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResponseBenefitDTO } from './responseBenefitDTO';


export interface ResponseUserDTO { 
    id?: string;
    nome?: string;
    cognome?: string;
    email?: string;
    dataDiNascita?: string;
    tipologia?: ResponseUserDTO.TipologiaEnum;
    pathImmagine?: string;
    sesso?: ResponseUserDTO.SessoEnum;
    dataRegistrazione?: string;
    punti?: number;
    vantaggio?: ResponseBenefitDTO;
}
export namespace ResponseUserDTO {
    export const TipologiaEnum = {
        Utente: 'UTENTE',
        Dipendente: 'DIPENDENTE',
        OrganizzatoreEventi: 'ORGANIZZATORE_EVENTI'
    } as const;
    export type TipologiaEnum = typeof TipologiaEnum[keyof typeof TipologiaEnum];
    export const SessoEnum = {
        Maschio: 'MASCHIO',
        Femmina: 'FEMMINA',
        NonSpecificato: 'NON_SPECIFICATO'
    } as const;
    export type SessoEnum = typeof SessoEnum[keyof typeof SessoEnum];
}


