/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResponseProductDTO } from './responseProductDTO';


export interface ResponseStockDTO { 
    filialeId?: string;
    filialeNome?: string;
    prodotto?: ResponseProductDTO;
    quantita?: number;
    quantitaPerNoleggio?: number;
}

