/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResponseProductDTO } from './responseProductDTO';


export interface ResponseOrderDetailsDTO { 
    ordineId?: string;
    prodotto?: ResponseProductDTO;
    utenteId?: string;
    quantita?: number;
}

