/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResponseReviewDTO { 
    id?: string;
    data?: string;
    numStelle?: number;
    descrizione?: string;
    prodottoNome?: string;
    utenteNome?: string;
    utenteCognome?: string;
}

