/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResponseRentalDetailsDTO { 
    noleggioId?: string;
    prodottoId?: string;
    prodottoNome?: string;
    prodottoDescrizione?: string;
    prodottoCostoGiornaliero?: number;
    prodottoPathImmagine?: string;
    organizzatoreEventiId?: string;
    quantita?: number;
}

