/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateEmployeeDTO { 
    id?: string;
    stipendio?: number;
    scadenzaContratto?: string;
    dataAssunzione?: string;
    filialeId?: string;
}

