/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdatePaymentMethodDTO { 
    id?: string;
    nomeSuCarta?: string;
    numero?: string;
    cvv?: string;
    dataScadenza?: string;
    paypalEmail?: string;
    tipoPagamento?: UpdatePaymentMethodDTO.TipoPagamentoEnum;
    isDefault?: boolean;
}
export namespace UpdatePaymentMethodDTO {
    export const TipoPagamentoEnum = {
        CartaDiCredito: 'CARTA_DI_CREDITO',
        Paypal: 'PAYPAL'
    } as const;
    export type TipoPagamentoEnum = typeof TipoPagamentoEnum[keyof typeof TipoPagamentoEnum];
}


